package: .
import:
- package: github.com/Sirupsen/logrus
- package: github.com/prometheus/client_golang
  subpackages:
  - prometheus
  - prometheus/promhttp
- package: github.com/matttproud/golang_protobuf_extensions
  subpackages:
  - pbutil
- package: github.com/prometheus/client_model
  subpackages:
  - go
