package: .
import:
- package: github.com/astaxie/beego
  version: ^1.9.2
  subpackages:
  - logs
- package: github.com/prometheus/client_golang
  subpackages:
  - prometheus
  - prometheus/promhttp
- package: github.com/matttproud/golang_protobuf_extensions
  subpackages:
  - pbutil
- package: github.com/prometheus/client_model
  subpackages:
  - go
